site_name: Obsidian MkDocs Material Documentation
site_url: https://allenlu12.github.io/COMP_2216_Obsidian_tutorial/
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
# extra:
#   social:
#     - icon: simple/youtube
#       link: https://youtube.com/@james-willett
#     - icon: simple/linkedin
#       link: https://linkedin.com/in/willettjames

nav:
  - Home: index.md
  - Tasks:
      - How to set up Obsidian and link notes: tasks/task1.md
      - How to format notes in Obsidian: tasks/task2.md
      - How to create and organize a knowledge base in Obsidian: tasks/task3.md
      - How to use and add plugins in Obsidian: tasks/task4.md
  - Glossary: glossary.md
  - Troubleshooting: troubleshooting.md
